//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ev1_RegistroAlumnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int id_alumno { get; set; }
        public string rut { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string direccion { get; set; }
        public int id_curso { get; set; }
    
        public virtual Curso Curso { get; set; }
    }
}
